# Site settings
baseurl = "https://teckup-tokyo.netlify.com/"
languageCode = "ja"
title = "TeckUp"
theme = "hugo-theme-cactus-plus"
# yumechi's googleAnalytics code
googleAnalytics = "UA-120509470-4"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[params]
	author = "TeckUp"
	description = "みんなでTeck Up！"
	bio = "「TeckUp」は、技術や専門領域に縛られず、成長したいと思う人たちが集まるコミュニティです。 「TeckUp」という名前は、技術(Technology)の「Tech」と成長を表す「Up」を組み合わせることで、「技術的に成長する人の集まり」という意味が込められています。 "

	twitter = "teckup_tokyo"
	facebook = ""

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "teckup"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = true


	enableGoogleAnalytics = true
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = "2019 TeckUp"

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = ""
	twitter-square = "https://www.twitter.com/teckup_tokyo"
	github-square = "https://www.github.com/teckup-tokyo"
